### ISSUE TITLE
Bug on April 2019?

### ISSUE THREAD

**Issue by atadioli** [jestrux/jquery-mini-event-calendar#7] opened 2019-03-19 18:10 UTC
Hi, script very well.
But I think that there is a little bug: April 2019 start with Sunday and not with Monday.

I don't know how to resolv it.

Thank you.

**Comment by jestrux** [comment] 2019-03-21 06:04
Hey @atadioli could you please check again? Because I checked both my phone and PC calendar and they both say it starts on April 1st is on monday.

![Screen Shot 2019-03-21 at 9 02 26 AM](https://user-images.githubusercontent.com/8426172/54735627-4a0de100-4bb8-11e9-9efd-a88cab3d9e18.png)

**Comment by atadioli** [comment] 2019-03-21 08:32
Hi,
I attach 2 screenshot.

![mec mar](https://user-images.githubusercontent.com/10436680/54740455-bb02c800-4bbb-11e9-9868-90723efd7c03.png)
![mec april](https://user-images.githubusercontent.com/10436680/54740456-bb02c800-4bbb-11e9-9a22-33dbf29f9083.png)

If I show the month of March, I see that April 1st is correct.
If I show the month of April, the first day is not correct.

Why?
Where am I wrong?

Thank you!

**Comment by jestrux** [comment] 2019-03-21 10:54
@atadioli Hello again, 

I found the error, I pushed some code in the last hour, that also includes a fix for this issue. 
Can you try again and see if it works?

Here are some screenshots I took after the fix.

![Screen Shot 2019-03-21 at 1 47 44 PM](https://user-images.githubusercontent.com/8426172/54747679-9e2cbb80-4be0-11e9-94a3-029e3bfd5932.png)

![Screen Shot 2019-03-21 at 1 47 24 PM](https://user-images.githubusercontent.com/8426172/54747689-a2f16f80-4be0-11e9-90b3-6bb5c663e39a.png)

**Comment by atadioli** [comment] 2019-03-22 09:23
Now works correctly!
Thank you! ;-)

**Comment by jestrux** [comment] 2019-03-22 10:31
Nice, glad I could help :)

**Comment by kylerfoulks** [comment] 2019-04-03 13:59
I can confirm that this update has fixed the issue. Thanks!

**Comment by atadioli** [comment] 2019-04-03 14:53
Wow, thank you!
When you to publish the update?
;-)



*Andrea Tadioli*
Digital Developer @ Seidigitale.com
Cellulare: (+39) 339.22.88.352
Site: www.seidigitale.com


Il giorno mer 3 apr 2019 alle ore 15:59 kylerfoulks <
notifications@github.com> ha scritto:

**Comment by jestrux** [comment] 2019-04-03 15:22
Thanks @kylerfoulks

**Closed as completed** 2020-03-05 09:58 UTC
