### ISSUE TITLE
Clicks are triggering postback on asp.net

### ISSUE THREAD

**Issue by premy** [jestrux/jquery-mini-event-calendar#5] opened 2018-09-24 00:36 UTC
Clicking on months or days is triggering a postback on asp.net Web Forms. I tried putting e.preventDefault() on the click functions; the postback does not happen any more but then the events are not displayed either.

**Comment by jestrux** [comment] 2018-09-24 05:13
Hey, could you recreate this problem in a fiddle or codepen so I can review it?

**Comment by premy** [comment] 2018-09-24 15:12
Hi, thank u for your answer. Thing is I tried using everything as is in an asp.net application. In plain html it works as expected but on an aspx page it causes a postback whenever you click on something on the calendar.
What I tried to do was adding this:
`
**mini_cal.on("click", function(e){
		  e.preventDefault();
		});`**
mini_cal.on("click, focusin", ".a-date", function(){
		    if(!$(this).hasClass('blurred'))
		        showEvent($(this).data('event'));
		});`
But then clicking on a day with event does not show the event in the footer.

**Comment by jestrux** [comment] 2019-04-18 06:38
@premy I pushed an update with a fix for this issue based on your suggestions in the issue #6 , could you please download again and verify if the issue is fixed?

**Closed as completed** 2020-03-05 10:09 UTC
